export const teamStadiumImages = [
  {
    id: 2005,
    school: "Air Force",
    stadiumImg:
      "https://images.sidearmdev.com/resize?url=https%3A%2F%2Fdxbhsrqyrr690.cloudfront.net%2Fsidearm.nextgen.sites%2Fgoairforcefalcons.com%2Fimages%2F2019%2F6%2F13%2FStadium_v_Navy_2_0062.JPG&height=1100&type=webp",
  },
  {
    id: 2006,
    school: "Akron",
    stadiumImg: "https://ohiostadiums.com/simages/1934.jpg",
  },
  {
    id: 333,
    school: "Alabama",
    stadiumImg:
      "https://dxbhsrqyrr690.cloudfront.net/sidearm.nextgen.sites/rolltide.com/images/2023/7/3/BDSRedLightsBand.jpg",
  },
  {
    id: 2026,
    school: "Appalachian State",
    stadiumImg:
      "https://www.newsobserver.com/latest-news/8kff1u/picture265168201/alternates/LANDSCAPE_1140/CLT_AppState34.JPG",
  },
  {
    id: 12,
    school: "Arizona",
    stadiumImg:
      "https://static.arizonawildcats.com/custompages/images/facilities/Arizona-Stadium-Cover.jpg",
  },
  {
    id: 9,
    school: "Arizona State",
    stadiumImg:
      "https://newsroom.asu.edu/sites/default/files/styles/panopoly_image_original/public/asu_ucla_full_0.jpg?itok=thI5VKoR",
  },
  {
    id: 8,
    school: "Arkansas",
    stadiumImg: "https://dwrrs.arkansasrazorbacks.com/open-graph.webp",
  },
  {
    id: 2032,
    school: "Arkansas State",
    stadiumImg:
      "https://www.astatefootball.com/images/140047609_1680713385434918_1873374413736982380_o.jpg",
  },
  {
    id: 349,
    school: "Army",
    stadiumImg:
      "https://static01.nyt.com/images/2021/09/11/sports/11cfb-army/11cfb-army-superJumbo.jpg",
  },
  {
    id: 2,
    school: "Auburn",
    stadiumImg:
      "https://images.sidearmdev.com/crop?url=https%3a%2f%2fdxbhsrqyrr690.cloudfront.net%2fsidearm.nextgen.sites%2fauburntigers.com%2fimages%2f2020%2f6%2f12%2f111117_GA_wr_618.jpg&height=400&width=1000&type=jpeg&gravity=smart",
  },
  { id: 2050, school: "Ball State", stadiumImg: null },
  { id: 239, school: "Baylor", stadiumImg: null },
  { id: 68, school: "Boise State", stadiumImg: null },
  { id: 103, school: "Boston College", stadiumImg: null },
  { id: 189, school: "Bowling Green", stadiumImg: null },
  { id: 2084, school: "Buffalo", stadiumImg: null },
  { id: 252, school: "BYU", stadiumImg: null },
  { id: 25, school: "California", stadiumImg: null },
  { id: 2117, school: "Central Michigan", stadiumImg: null },
  { id: 2429, school: "Charlotte", stadiumImg: null },
  { id: 2132, school: "Cincinnati", stadiumImg: null },
  { id: 228, school: "Clemson", stadiumImg: null },
  { id: 324, school: "Coastal Carolina", stadiumImg: null },
  { id: 38, school: "Colorado", stadiumImg: null },
  { id: 36, school: "Colorado State", stadiumImg: null },
  { id: 41, school: "Connecticut", stadiumImg: null },
  { id: 150, school: "Duke", stadiumImg: null },
  { id: 151, school: "East Carolina", stadiumImg: null },
  { id: 2199, school: "Eastern Michigan", stadiumImg: null },
  { id: 57, school: "Florida", stadiumImg: null },
  { id: 2226, school: "Florida Atlantic", stadiumImg: null },
  { id: 2229, school: "Florida International", stadiumImg: null },
  { id: 52, school: "Florida State", stadiumImg: null },
  { id: 278, school: "Fresno State", stadiumImg: null },
  {
    id: 61,
    school: "Georgia",
    stadiumImg:
      "https://thegeorgiabulldogclub.com/wp-content/uploads/2019/10/page-wchf-m-1466x823.jpg",
  },
  { id: 290, school: "Georgia Southern", stadiumImg: null },
  { id: 2247, school: "Georgia State", stadiumImg: null },
  { id: 59, school: "Georgia Tech", stadiumImg: null },
  { id: 62, school: "Hawai'i", stadiumImg: null },
  { id: 248, school: "Houston", stadiumImg: null },
  { id: 356, school: "Illinois", stadiumImg: null },
  { id: 84, school: "Indiana", stadiumImg: null },
  { id: 2294, school: "Iowa", stadiumImg: null },
  { id: 66, school: "Iowa State", stadiumImg: null },
  { id: 55, school: "Jacksonville State", stadiumImg: null },
  { id: 256, school: "James Madison", stadiumImg: null },
  { id: 2305, school: "Kansas", stadiumImg: null },
  { id: 2306, school: "Kansas State", stadiumImg: null },
  { id: 2309, school: "Kent State", stadiumImg: null },
  { id: 96, school: "Kentucky", stadiumImg: null },
  { id: 2335, school: "Liberty", stadiumImg: null },
  { id: 309, school: "Louisiana", stadiumImg: null },
  { id: 2433, school: "Louisiana Monroe", stadiumImg: null },
  { id: 2348, school: "Louisiana Tech", stadiumImg: null },
  { id: 97, school: "Louisville", stadiumImg: null },
  { id: 99, school: "LSU", stadiumImg: null },
  { id: 276, school: "Marshall", stadiumImg: null },
  { id: 120, school: "Maryland", stadiumImg: null },
  { id: 235, school: "Memphis", stadiumImg: null },
  { id: 2390, school: "Miami", stadiumImg: null },
  { id: 193, school: "Miami (OH)", stadiumImg: null },
  {
    id: 130,
    school: "Michigan",
    stadiumImg:
      "https://dxbhsrqyrr690.cloudfront.net/sidearm.nextgen.sites/mgoblue.com/images/2014/8/28/10254684.jpeg",
  },
  { id: 127, school: "Michigan State", stadiumImg: null },
  { id: 2393, school: "Middle Tennessee", stadiumImg: null },
  { id: 135, school: "Minnesota", stadiumImg: null },
  { id: 344, school: "Mississippi State", stadiumImg: null },
  {
    id: 142,
    school: "Missouri",
    stadiumImg:
      "https://images.sidearmdev.com/crop?url=https%3a%2f%2fdxbhsrqyrr690.cloudfront.net%2fsidearm.nextgen.sites%2fmutigers.com%2fimages%2f2015%2f7%2f9%2f8267679_1_.jpeg&height=563&width=1000&type=jpeg&gravity=smart",
  },
  { id: 2426, school: "Navy", stadiumImg: null },
  { id: 152, school: "NC State", stadiumImg: null },
  { id: 158, school: "Nebraska", stadiumImg: null },
  { id: 2440, school: "Nevada", stadiumImg: null },
  { id: 167, school: "New Mexico", stadiumImg: null },
  { id: 166, school: "New Mexico State", stadiumImg: null },
  { id: 153, school: "North Carolina", stadiumImg: null },
  { id: 2459, school: "Northern Illinois", stadiumImg: null },
  { id: 249, school: "North Texas", stadiumImg: null },
  { id: 77, school: "Northwestern", stadiumImg: null },
  { id: 87, school: "Notre Dame", stadiumImg: null },
  { id: 195, school: "Ohio", stadiumImg: null },
  {
    id: 194,
    school: "Ohio State",
    stadiumImg:
      "https://images.sidearmdev.com/resize?url=https%3A%2F%2Fdxbhsrqyrr690.cloudfront.net%2Fsidearm.nextgen.sites%2Fohiostatebuckeyes.com%2Fimages%2F2023%2F8%2F30%2Fhomecoming-8.jpg&width=1128&type=webp",
  },
  { id: 201, school: "Oklahoma", stadiumImg: null },
  { id: 197, school: "Oklahoma State", stadiumImg: null },
  { id: 295, school: "Old Dominion", stadiumImg: null },
  { id: 145, school: "Ole Miss", stadiumImg: null },
  { id: 2483, school: "Oregon", stadiumImg: null },
  { id: 204, school: "Oregon State", stadiumImg: null },
  { id: 213, school: "Penn State", stadiumImg: null },
  { id: 221, school: "Pittsburgh", stadiumImg: null },
  { id: 2509, school: "Purdue", stadiumImg: null },
  { id: 242, school: "Rice", stadiumImg: null },
  { id: 164, school: "Rutgers", stadiumImg: null },
  { id: 2534, school: "Sam Houston State", stadiumImg: null },
  { id: 21, school: "San Diego State", stadiumImg: null },
  { id: 23, school: "San José State", stadiumImg: null },
  { id: 2567, school: "SMU", stadiumImg: null },
  { id: 6, school: "South Alabama", stadiumImg: null },
  { id: 2579, school: "South Carolina", stadiumImg: null },
  { id: 2572, school: "Southern Mississippi", stadiumImg: null },
  { id: 58, school: "South Florida", stadiumImg: null },
  { id: 24, school: "Stanford", stadiumImg: null },
  { id: 183, school: "Syracuse", stadiumImg: null },
  { id: 2628, school: "TCU", stadiumImg: null },
  { id: 218, school: "Temple", stadiumImg: null },
  { id: 2633, school: "Tennessee", stadiumImg: null },
  { id: 251, school: "Texas", stadiumImg: null },
  { id: 245, school: "Texas A&M", stadiumImg: null },
  { id: 326, school: "Texas State", stadiumImg: null },
  { id: 2641, school: "Texas Tech", stadiumImg: null },
  { id: 2649, school: "Toledo", stadiumImg: null },
  { id: 2653, school: "Troy", stadiumImg: null },
  { id: 2655, school: "Tulane", stadiumImg: null },
  { id: 202, school: "Tulsa", stadiumImg: null },
  { id: 5, school: "UAB", stadiumImg: null },
  { id: 2116, school: "UCF", stadiumImg: null },
  { id: 26, school: "UCLA", stadiumImg: null },
  { id: 113, school: "UMass", stadiumImg: null },
  { id: 2439, school: "UNLV", stadiumImg: null },
  { id: 30, school: "USC", stadiumImg: null },
  { id: 254, school: "Utah", stadiumImg: null },
  { id: 328, school: "Utah State", stadiumImg: null },
  { id: 2638, school: "UTEP", stadiumImg: null },
  { id: 2636, school: "UT San Antonio", stadiumImg: null },
  { id: 238, school: "Vanderbilt", stadiumImg: null },
  { id: 258, school: "Virginia", stadiumImg: null },
  { id: 259, school: "Virginia Tech", stadiumImg: null },
  { id: 154, school: "Wake Forest", stadiumImg: null },
  { id: 264, school: "Washington", stadiumImg: null },
  { id: 265, school: "Washington State", stadiumImg: null },
  { id: 98, school: "Western Kentucky", stadiumImg: null },
  { id: 2711, school: "Western Michigan", stadiumImg: null },
  { id: 277, school: "West Virginia", stadiumImg: null },
  { id: 275, school: "Wisconsin", stadiumImg: null },
  { id: 2751, school: "Wyoming", stadiumImg: null },
];
